# Generated by Django 3.1.3 on 2020-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='color',
            field=models.CharField(choices=[('#FFBEDA', 'red'), ('#FFC7AF', 'orange'), ('#FFFF88', 'yellow'), ('#FF77FF', 'pink'), ('#DCC2FF', 'purple'), ('#B1F9D0', 'green'), ('#BAD3FF', 'blue')], default='blue', max_length=10),
        ),
    ]
